# Generated by Django 5.1.1 on 2024-09-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="training",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="training",
            old_name="trainer_id",
            new_name="trainer",
        ),
    ]
