# Generated by Django 5.1.1 on 2024-09-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0002_rename_category_id_training_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="available_seats",
            field=models.PositiveIntegerField(default=models.PositiveIntegerField()),
        ),
    ]
