# Generated by Django 5.1.1 on 2024-09-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0003_alter_training_available_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="available_seats",
            field=models.PositiveIntegerField(),
        ),
    ]
